language: node_js
dist: trusty
sudo: false
node_js:
  - '8'
cache: npm
deploy:
  provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    repo: Feeles/IDE
    all_branches: true
notifications:
  slack:
    rooms:
      - hackforplay:3ZXJmUzsYmjM86Ty3oXOvqpC
    on_success: never
env:
  global:
    - secure: uNUhm8ym7ziZD6aBx/rdspLEbHomiXtYkSDQ4NiUox3oYPQN4e586QW4sbyKKiS4f844q5z3bvZLm1ucHXeUy6h0iscK48QbrcGwmVdY9eCi6Ve3CrMIInM78jo0AWMTNeA5LBjQRBQX3h3N2+dCCNcghXp6TYEabf2K4lipqHXs2lyBEt4uDi7RjUviHUofMNBn3nqrbUm2BITYndZX9lBDweOE2CxdD42WH8Swh6DVb2mTu+Z/0+9YNyjAcs4K1J6tdgmR5T3swPpuyE8KbecqD5VHTAdAADOhDnm8Oi5R0TiSYcR6EoIOOaQDGdv5R/aOUtJ666dbPnEPMRVJey43tUzR2R6h6zrLxNpm6AMy2kwl1hikWyLr8E8DOh7MF5n+ipfTj9msrROq1uHIHpz4zLjdS+cxWIHB1l47aJRzSvHSHD1DXi4DjhZKSyBhPLCdaLCupERg+NUrFzgacnxLBfw7yfmdLjp+Dj6OUw9JQr9kjdbuj3CJSQRuMLNbYdllXTBd8uLsklVbSvr7Cbt1VNTd4IpNjjN7Y0Jjhrs5RHpQH1KB2EE1w71/JiTzguYbIWAiwU/yetCvzFWYV8uaBUx7DI/skpB9qWoX+Y4R4voAQXuLroFWVGymyYQbpQPdD+RD5cXmeafHFlqn9fseBNgZfwxF1aXSTmXW1Qg=
    - secure: h0VBS/uC/+SDsd2U7aDASjB/+WJ20jLNdfCzXVyZ9uKZGuTJtLadqh0stYC+RfmebqBjzcEqUGxJrgWN8suYHHAenT+1usH7iu3r6/6mMYU8c9S8yjM3Yzvvpr74oIG9uJbZRj20mH37kQy8IapgOYtoT9vkEuEypr6EG+7mNTLVvaeqkBKZjoi4QIw3isEKm0AtHF0AHaOrnYC2lg6ZB5wYxV228WXbyQTP275jQ2SsNcPW9Sgp5gGZ59gq+Mk5CEZLLD9i/1BNj3kGx3QtuCo2tazblbH6zQ+qi0vY8hTGlEezmimpcMRI6nui0iWgtWCGIMohUc4oKLHbGWmDNHW5rH72gQC3WGtrXHq0zHQVazEdqlPjpEXrh1tVNbuOlP/W936Gziz1RIctk8gwGgsW9iU7kfNZumkooNARAMtCnVQQOwXav2fIPpflMgKLc3klPuz2fMQ34v79FVDuAYy7izK03WoiW5begIHFCWI2HiqTiI7KhfBXNA8ah0myuhjBXhjZculCcomAEh7M/PIz8/r0mu2Bb02O0D7gEGaXmNs1i4cr8X0j2pq0uSJIQKcggO3JWVRC6mSw+RJgaew8FtsO6MErxrGvmIFDImqJyWE5lql4Ylj+uWdaiX+s7j/gBxqapGHWPtAbooXCTKT1RN5YztsVBGaxO2Ae+ws=
