language: node_js
dist: trusty
sudo: false
node_js:
  - '8'

deploy:
  provider: script
  script: npx semantic-release
  skip_cleanup: true
  on:
    repo: teramotodaiki/feeles-ide
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|release.*)$ # "master" or "releaseから始まる任意のブランチ" のみデプロイ

notifications:
  slack:
    rooms:
      - hackforplay:3ZXJmUzsYmjM86Ty3oXOvqpC
    on_success: never
